# Generated by Django 2.0 on 2018-07-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0014_auto_20180724_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_logo',
            field=models.FileField(default='', max_length=500, upload_to=''),
        ),
    ]
