# Generated by Django 2.2.dev20180722064755 on 2018-07-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EFiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='efile',
            name='file_author',
            field=models.CharField(default='Aryaz', max_length=100),
            preserve_default=False,
        ),
    ]
