# Generated by Django 2.0 on 2018-07-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EFiles', '0002_efile_file_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='efile',
            name='book_logo',
            field=models.FileField(default='', max_length=500, upload_to=''),
        ),
    ]
