# Generated by Django 2.0 on 2018-07-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EFiles', '0003_efile_book_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efile',
            name='book_logo',
        ),
    ]
